apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: o6492mmv1-python 
  janus-idp.io/tekton: o6492mmv1-python
  backstage.io/kubernetes-id: o6492mmv1-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o6492mmv1-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml